name: Build nest app

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nest-graphql-mongodb

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS 16.8-alpine
        uses: actions/setup-node@v1
        with:
          node-version: 16.8-alpine

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build