name: Test and Build

on:
  pull_request:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: cd /hobb-next-app
        run: cd hobb-next-app

      - name: Build
        run: yarn build /hobb-next-app 