name: Test and Build

on:
  pull_request:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: change to hobby-next-app folder
        run: cd hobby-next-app

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build